# Generated by Django 2.1.7 on 2019-03-02 00:25

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('ctitle', models.CharField(max_length=20, verbose_name='Category title')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Product name')),
                ('image', models.ImageField(upload_to='product', verbose_name='product image path')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Product price')),
                ('clicks', models.IntegerField(verbose_name='the number of clicks of a product')),
                ('description', models.CharField(max_length=200, verbose_name='product description')),
                ('stock', models.IntegerField(verbose_name='products in stock')),
                ('detail', tinymce.models.HTMLField(max_length=200, verbose_name='product details')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='product category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
