# Generated by Django 2.1.7 on 2019-03-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='clicks',
            new_name='click',
        ),
    ]
