# Generated by Django 2.1.7 on 2019-03-23 10:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190321_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=tinymce.models.HTMLField(max_length=3000, verbose_name='product details'),
        ),
    ]
