# Generated by Django 2.1.7 on 2019-03-05 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190305_1244'),
        ('cart', '0003_auto_20190305_1244'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=100, verbose_name='address')),
                ('re_address', models.CharField(default='', max_length=20, verbose_name='recipient address')),
                ('zip', models.CharField(default='', max_length=6, verbose_name='zip code')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='phone number')),
            ],
        ),
        migrations.AlterField(
            model_name='productbrowser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
