# Generated by Django 2.1.7 on 2019-03-02 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='order id')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='date')),
                ('has_payed', models.BooleanField(default=False, verbose_name='payment status')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='total price')),
                ('address', models.CharField(max_length=150, verbose_name='order address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='order user')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='product price')),
                ('count', models.IntegerField(verbose_name='quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Order detail',
                'verbose_name_plural': 'Order details',
            },
        ),
    ]
